In [41]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

import warnings

warnings.filterwarnings('ignore')

In [42]:
train = pd.read_csv(r'/content/drive/MyDrive/TRAINING_.csv',header=0,index_col=0)


In [43]:
train

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms roof  Roof(Area)  \
id                                                                              
1             305    8.0        2.0          1.0         3.0   NO         0.0   
2             344    6.0        7.0          7.0         8.0   no         0.0   
3             294    8.0        4.0          3.0         4.0  yes        97.0   
4             328    5.0        4.0          2.0         4.0   NO         0.0   
5             295    9.0        5.0          3.0         5.0  NaN         NaN   
...           ...    ...        ...          ...         ...  ...         ...   
6996          306    8.0        2.0          1.0         3.0  NaN         NaN   
6997          341    5.0        3.0          2.0         4.0  YES       100.0   
6998          306    6.0        4.0          2.0         4.0  yes        83.0   
6999          338    8.0        7.0          6.0         7.0   NO         0.0   
7000          314    5.0        6.0          4.0         6.0  yes       109.0   

      Lawn(Area)  Nfloors   API  ANB Grade EXPECTED  
id                                                   
1           76.0        2  63.0    4     D    3826$  
2           83.0        7  97.0    1     B    4458$  
3           78.0        1  88.0    4     C    4199$  
4           91.0        5  86.0    1     D    3462$  
5           97.0        4  93.0    3     C    4543$  
...          ...      ...   ...  ...   ...      ...  
6996        78.0        1  73.0    5     D    3717$  
6997        72.0        4  76.0    4     D    3339$  
6998        80.0        4  96.0    4     D    3829$  
6999        95.0        4  84.0    1     B    4488$  
7000        80.0        4  96.0    2     C    3418$  

[7000 rows x 13 columns]

In [44]:
train.isnull().sum()

Area(total)       0
Troom             2
Nbedrooms         3
Nbwashrooms       2
Twashrooms        1
roof           1353
Roof(Area)     1353
Lawn(Area)        2
Nfloors           0
API               1
ANB               0
Grade             0
EXPECTED          0
dtype: int64

In [45]:
train.duplicated().sum()

0

In [46]:
train.dtypes

Area(total)      int64
Troom          float64
Nbedrooms      float64
Nbwashrooms    float64
Twashrooms     float64
roof            object
Roof(Area)     float64
Lawn(Area)     float64
Nfloors          int64
API            float64
ANB              int64
Grade           object
EXPECTED        object
dtype: object

In [47]:
train.describe(include='all')

Area(total)        Troom    Nbedrooms  Nbwashrooms   Twashrooms  roof  \
count   7000.000000  6998.000000  6997.000000  6998.000000  6999.000000  5647   
unique          NaN          NaN          NaN          NaN          NaN     4   
top             NaN          NaN          NaN          NaN          NaN    no   
freq            NaN          NaN          NaN          NaN          NaN  1436   
mean     325.225571     7.012146     4.992568     4.004716     5.501357   NaN   
std       20.550583     1.420061     1.653418     1.596984     1.509129   NaN   
min      290.000000     5.000000     2.000000     1.000000     3.000000   NaN   
25%      307.000000     6.000000     4.000000     3.000000     4.000000   NaN   
50%      326.000000     7.000000     5.000000     4.000000     5.000000   NaN   
75%      343.000000     8.000000     6.000000     5.000000     7.000000   NaN   
max      360.000000     9.000000     8.000000     7.000000     8.000000   NaN   

         Roof(Area)   Lawn(Area)      Nfloors          API          ANB Grade  \
count   5647.000000  6998.000000  7000.000000  6999.000000  7000.000000  7000   
unique          NaN          NaN          NaN          NaN          NaN     5   
top             NaN          NaN          NaN          NaN          NaN     C   
freq            NaN          NaN          NaN          NaN          NaN  2928   
mean      47.202763    89.957988     4.509429    78.975711     3.494714   NaN   
std       48.806472    11.812719     1.831187    11.852443     1.700449   NaN   
min        0.000000    70.000000     1.000000    59.000000     1.000000   NaN   
25%        0.000000    80.000000     3.000000    69.000000     2.000000   NaN   
50%        0.000000    90.000000     5.000000    79.000000     3.000000   NaN   
75%       95.000000   100.000000     6.000000    89.000000     5.000000   NaN   
max      120.000000   110.000000     8.000000    99.000000     6.000000   NaN   

       EXPECTED  
count      7000  
unique     2042  
top       3963$  
freq         15  
mean        NaN  
std         NaN  
min         NaN  
25%         NaN  
50%         NaN  
75%         NaN  
max         NaN

In [48]:
for i in train.columns:
  print({i:train[i].unique()})

{'Area(total)': array([305, 344, 294, 328, 295, 335, 322, 346, 298, 329, 304, 307, 316,
       351, 312, 318, 359, 339, 291, 313, 348, 349, 357, 336, 301, 311,
       309, 337, 334, 360, 347, 319, 356, 315, 355, 317, 302, 296, 343,
       330, 338, 290, 321, 333, 352, 350, 354, 306, 342, 324, 331, 293,
       320, 303, 300, 353, 332, 297, 326, 323, 327, 340, 292, 358, 314,
       299, 308, 325, 310, 341, 345])}
{'Troom': array([ 8.,  6.,  5.,  9.,  7., nan])}
{'Nbedrooms': array([ 2.,  7.,  4.,  5.,  6.,  3.,  8., nan])}
{'Nbwashrooms': array([ 1.,  7.,  3.,  2.,  5.,  4.,  6., nan])}
{'Twashrooms': array([ 3.,  8.,  4.,  5.,  7.,  6., nan])}
{'roof': array(['NO', 'no', 'yes', nan, 'YES'], dtype=object)}
{'Roof(Area)': array([  0.,  97.,  nan, 112.,  83.,  72.,  92.,  77.,  94., 108., 102.,
       106.,  95.,  80., 118.,  74.,  78.,  85.,  98., 109., 113.,  84.,
       101., 100., 119.,  75., 103.,  71.,  88., 120., 114.,  82.,  96.,
        91., 105., 111.,  76.,  90.,  81., 107., 115

In [49]:
train.roof.unique()

array(['NO', 'no', 'yes', nan, 'YES'], dtype=object)

In [50]:
train.dropna(subset=['Troom'],inplace=True)

In [51]:
train.dropna(subset=['Nbedrooms'],inplace=True)

In [52]:
train.dropna(subset=['Nbwashrooms'],inplace=True)

In [53]:
train.dropna(subset=['Twashrooms'],inplace=True)

In [54]:
train.dropna(subset=['Lawn(Area)'],inplace=True)

In [55]:
train.dropna(subset=['API'],inplace=True)

In [56]:
train.dropna(subset=['roof'],inplace=True)

In [57]:
train.dropna(subset=['Roof(Area)'],inplace=True)

In [58]:
train.drop(['Roof(Area)'],axis=1,inplace=True)

In [59]:
train.shape

(5637, 12)

In [60]:
train.roof.unique()

array(['NO', 'no', 'yes', 'YES'], dtype=object)

In [61]:
train['roof'] = train['roof'].str.lower()
roof_mapping = {'no': 'No',
                'yes': 'Yes'}



In [62]:
train['roof'] = train['roof'].map(roof_mapping)

In [63]:
train['roof'].fillna('N/A', inplace=True)

In [64]:
col=[]
for x in train.columns:
  if train[x].dtypes == "object":
    col.append(x)


In [65]:
x

'EXPECTED'

In [66]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
for x in col:
    train[x]=le.fit_transform(train[x])

In [67]:
train

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms  roof  \
id                                                                   
1             305    8.0        2.0          1.0         3.0     0   
2             344    6.0        7.0          7.0         8.0     0   
3             294    8.0        4.0          3.0         4.0     1   
4             328    5.0        4.0          2.0         4.0     0   
6             335    8.0        6.0          5.0         7.0     0   
...           ...    ...        ...          ...         ...   ...   
6995          314    7.0        7.0          5.0         6.0     1   
6997          341    5.0        3.0          2.0         4.0     1   
6998          306    6.0        4.0          2.0         4.0     1   
6999          338    8.0        7.0          6.0         7.0     0   
7000          314    5.0        6.0          4.0         6.0     1   

      Lawn(Area)  Nfloors   API  ANB  Grade  EXPECTED  
id                                                     
1           76.0        2  63.0    4      3       742  
2           83.0        7  97.0    1      1      1362  
3           78.0        1  88.0    4      2      1110  
4           91.0        5  86.0    1      3       384  
6           99.0        6  75.0    1      2      1231  
...          ...      ...   ...  ...    ...       ...  
6995        72.0        5  98.0    3      2      1128  
6997        72.0        4  76.0    4      3       273  
6998        80.0        4  96.0    4      3       745  
6999        95.0        4  84.0    1      1      1389  
7000        80.0        4  96.0    2      2       345  

[5637 rows x 12 columns]

In [68]:
train.dtypes

Area(total)      int64
Troom          float64
Nbedrooms      float64
Nbwashrooms    float64
Twashrooms     float64
roof             int64
Lawn(Area)     float64
Nfloors          int64
API            float64
ANB              int64
Grade            int64
EXPECTED         int64
dtype: object

In [69]:
column = train.columns.tolist()
column = column[:-2] + [column[-1]] + [column[-2]]
train = train[column]


In [70]:
x=train.values[:,0:-1]
y=train.values[:,-1]

In [71]:
print(x.shape)
print(y.shape)

(5637, 11)
(5637,)


In [72]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(x)
trans=scaler.transform(x)


In [73]:
print(trans)

[[-0.9810016   0.69518235 -1.82862028 ... -1.35346978  0.2891817
  -0.39334259]
 [ 0.91568317 -0.71291787  1.21817935 ...  1.51077631 -1.47628822
   0.96323416]
 [-1.51596397  0.69518235 -0.60990043 ...  0.75259352  0.2891817
   0.41185135]
 ...
 [-0.93236866 -0.71291787 -0.60990043 ...  1.42653378  0.2891817
  -0.38677851]
 [ 0.62388551  0.69518235  1.21817935 ...  0.41562339 -1.47628822
   1.02231089]
 [-0.54330512 -1.41696799  0.60881943 ...  1.42653378 -0.88779825
  -1.26198932]]


In [74]:
#Running a basic model
from sklearn.model_selection import train_test_split

#Split the data into test and train
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=10)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
#pirnt("percent of train data",X_trin.shape[0]/X.Shape[0]*100)

(4509, 11)
(4509,)
(1128, 11)
(1128,)


In [75]:
from sklearn.tree import DecisionTreeClassifier

Tree=DecisionTreeClassifier(random_state=10, splitter="best",
                            criterion="gini",
                             max_depth=10)
Tree.fit(x_train,y_train)

y_pred=Tree.predict(x_test)

print(list(zip(y_test,y_pred)))

[(2.0, 2.0), (2.0, 2.0), (1.0, 0.0), (3.0, 3.0), (1.0, 2.0), (0.0, 0.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (2.0, 3.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (3.0, 3.0), (3.0, 3.0), (3.0, 3.0), (3.0, 3.0), (1.0, 1.0), (3.0, 3.0), (2.0, 3.0), (3.0, 3.0), (3.0, 3.0), (3.0, 3.0), (2.0, 1.0), (3.0, 3.0), (2.0, 2.0), (0.0, 0.0), (2.0, 2.0), (3.0, 3.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (1.0, 2.0), (3.0, 3.0), (3.0, 3.0), (3.0, 3.0), (1.0, 1.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (3.0, 3.0), (2.0, 3.0), (1.0, 1.0), (1.0, 1.0), (3.0, 3.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (3.0, 3.0), (1.0, 2.0), (4.0, 3.0), (2.0, 2.0), (2.0, 2.0), (3.0, 3.0), (3.0, 3.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (1.0, 1.0), (1.0, 1.0), (2.0, 2.0), (2.0, 2.0), (3.0, 3.0), (3.0, 3.0), (2.0, 2.0), (1.0, 1.0), (3.0, 3.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (1.0, 2.0), (3.0, 3.0), (2.

In [76]:
Tree.score(x_train,y_train)

0.941672211133289

In [77]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 44  24   0   0   0]
 [ 11 177  37   0   0]
 [  1  47 361  42   0]
 [  0   1  55 324   0]
 [  0   0   0   4   0]]
0.8031914893617021
              precision    recall  f1-score   support

         0.0       0.79      0.65      0.71        68
         1.0       0.71      0.79      0.75       225
         2.0       0.80      0.80      0.80       451
         3.0       0.88      0.85      0.86       380
         4.0       0.00      0.00      0.00         4

    accuracy                           0.80      1128
   macro avg       0.63      0.62      0.62      1128
weighted avg       0.80      0.80      0.80      1128



comparing with logistic regression

In [78]:
from sklearn.linear_model import LogisticRegression
#create a model object
classifier = LogisticRegression()
#train the model object
classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)
print(y_pred)

[2. 2. 1. ... 2. 2. 2.]


In [79]:
#print(list(zip(Y_test,Y_pred)))

print(list(zip(train.columns[:-1],classifier.coef_.ravel())))

[('Area(total)', -0.02475465217780319), ('Troom', -0.0006354602751851808), ('Nbedrooms', 0.004236902387953272), ('Nbwashrooms', 0.005613064272740725), ('Twashrooms', 0.003343387564422486), ('roof', 0.0007682909355982098), ('Lawn(Area)', -0.04860480429902431), ('Nfloors', 0.009312263696633563), ('API', -0.03286556789653145), ('ANB', -0.0021743517066536685), ('EXPECTED', 0.01267958845467327)]


In [80]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test, y_pred)
print("Accuracy of the modle: ",acc)

[[ 27  41   0   0   0]
 [ 18 116  91   0   0]
 [  0  49 310  92   0]
 [  0   0 119 261   0]
 [  0   0   0   4   0]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.60      0.40      0.48        68
         1.0       0.56      0.52      0.54       225
         2.0       0.60      0.69      0.64       451
         3.0       0.73      0.69      0.71       380
         4.0       0.00      0.00      0.00         4

    accuracy                           0.63      1128
   macro avg       0.50      0.46      0.47      1128
weighted avg       0.63      0.63      0.63      1128

Accuracy of the modle:  0.6329787234042553
